### ISSUE TITLE
QUESTION: is it free to take part in ? any good first issue for beginner?

### ISSUE THREAD

**Issue by noneback** [oasysai/oasysdb#33]
Got interested in that project. I am a rust beginner and know a little about vector database and how hnsw is implemented. :)
Is it free to take part in and Any good first issue for beginner? Hope to write some code for this project.

**Comment by edwinkys** [comment]
Hey, thank you for considering to contribute. To answer your question, yes, OasysDB is open-source and free for all. If you don't mind sharing, are you familiar with benchmarking vector database? Like for example, measuring Recall rate or QPS?

**Comment by noneback** [comment]
I'm not that familiar with vector database benchmarking. Are there any reading materials or stuff like that?

**Comment by edwinkys** [comment]
I see. I'm not quite familiar with that type of benchmarking myself. I have to research about that a little bit more too. The resource that you provided is actually a good one. But, like you said, often times, benchmarking differs from machine to machine.

Currently, the usage is pretty low so beside what I'm focusing on right now which is to make it interoperable with Python or benchmarking, there is nothing else yet.

Would you mind joining the Discord just in case there is a good first issue, I can inform you immediately.

**Comment by noneback** [comment]
Sure. I will join the discord and wait for a suitable issue.

**Comment by noneback** [comment]
The discord link on readme doc seems inaccessible to me.

**Comment by edwinkys** [comment]
Hey, I apologize for that: This is the link that I have tested: https://discord.gg/bDhQrkqNP4.
