### ISSUE TITLE
FEAT: add another distance metrics

### ISSUE THREAD

**Issue by edwinkys** [oasysai/oasysdb#38]
### Use case

OasysDB uses Euclidean distance formula to measure the distance between vectors by default. Some use cases of the users might require them to use other distance metrics like Dot Product or Cosine Similariy.

### Proposed solution

I think the best solution would be to allow users to configure the distance formula choice in the Collection configuration level. Something like:

```rs
pub struct Config {
    ...
    distance: String
}
```

Then after that, in the `Vector` implementation:

```rs
pub fn distance(&self, other: &Self, formula: &str) -> f32 {...}
```

**Comment by noneback** [comment]
Want to tackle it

**Comment by edwinkys** [comment]
Thank you for your interest in contributing to make this project better. Let me know if you have any suggestions or roadblocks when tackling this issue. I'd be happy to provide you with some assistance.

**Comment by noneback** [comment]
1. A config entry to allow users to set distance calculation methods.
2. I guess we can provide an enum of common `DistanceCalculation` for users to choose so that we can hide the implementation details.

Do we need to provide a flexible way to customize the distance calculation, like, making the calculation a more abstract function to set?

**Comment by noneback** [comment]
And I find `Vector` stores data in Vec, using iter to calculate distance.
`        iter.map(|(a, b)| (a - b).powi(2)).sum::<f32>().sqrt()
`
Can we use some algebra crate like [nalgebra](https://github.com/dimforge/nalgebra) to accelerate calculation?

**Comment by edwinkys** [comment]
Hey, we could definitely start with optimizing the distance calculation using `nalgebra` crate.

Could you run the benchmark before and after the change too?

It’d be great if you can open a PR on this change first to keep the PR small and easy to merge.

Thank you in advance!

**Comment by edwinkys** [comment]
As for the distance calculation formula, if not for the Python interoperability issues, I would’ve totally agree with your approach since it’s much more flexible and safe.

But because of Python interoperability, I plan to keep it really simple. That’s why I was thinking of using simple string added to the Config and add a validator when creating the config to make sure the distance formula is supported.

Please let me know your thoughts.

**Comment by noneback** [comment]
> Hey, we could definitely start with optimizing the distance calculation using `nalgebra` crate. Could you run the benchmark before and after the change so we can see if there is really any improvement by adding this new dependencies.
> 
> It’d be great if you can open a PR on this change first to keep the PR small and easy to merge. Thank you in advance!

Sure. I will open a new PR to keep track of this change and do a benchmark test to see if it worth

**Comment by noneback** [comment]
> As for the distance calculation formula, if not for the Python interoperability issues, I would’ve totally agree with your approach of adding the enum and/or trait to customize the distance formula since it’s much more flexible and safe.
> 
> But because of Python interoperability, I plan to keep it really simple. That’s why I was thinking of using a simple string added to the Config and adding a validator when creating the config to make sure the distance formula is supported.
> 
> Please let me know your thoughts.

I get your point. I guess using some simple built-in data structure would be a better choice considering interoperability. We can provide some common distance calculations such as Dot, Cosine, and Euclidean. Users set calculations using `string` and we validate if we support or not.

**Comment by edwinkys** [comment]
That's correct! Using built-in data structure keeps the implementation simple and paired with validation, it should suffice.

**Comment by noneback** [comment]
I prefer to make distance calculation an attribute of `Collection` rather than `Vector`'s . Cuz I notice distance calculating is a func of `Vector`.

**Comment by noneback** [comment]
like
```rust
pub enum Distance {
    Dot,
    Euclidean,
    Cosine,
}
...
pub struct Collection {
    /// The collection configuration object.
    #[pyo3(get)]
    pub config: Config,
    // Private fields below.
    data: HashMap<VectorID, Metadata>,
    vectors: HashMap<VectorID, Vector>,
    slots: Vec<VectorID>,
    base_layer: Vec<BaseNode>,
    upper_layers: Vec<Vec<UpperNode>>,
    // Utility fields.
    count: usize,
    dimension: usize,
    distance: Distance,
}

```

**Comment by edwinkys** [comment]
Hey, I'm just curious, is there a specific reason why you prefer to make the distance calculation as attributes of `Collection` instead of a method in the `Vector`?

**Comment by noneback** [comment]
> Hey, I'm just curious, is there a specific reason why you prefer to make the distance calculation as attributes of `Collection` instead of a method in the `Vector`?
> 
> Edit: Nevermind my question above. After thinking about it, it does make sense as distance is only used in indexing. With that being said, can we have the distance as part of `Config`? So that users can easily set it up along with other index-related configurations.

I think `Vector` is more like a container for those float values, and `distance` is an independent attribute between two `Vector`. Attaching distance calculation to **A single `Vector`** is a little bit easy to misunderstand considering we put Vectors into a `Collection`. We can sure make distance as part of HNSW Config, because it is exactly where we are to use iit.

**Comment by noneback** [comment]
Maybe I can make a PR if it sounds acceptable and discuss more about it

**Comment by edwinkys** [comment]
Thank you for the explanation, it makes sense. I'm looking forward to reviewing and potentially merging the PR to the project.

**Comment by noneback** [comment]
> Thank you for the explanation, it makes sense. I'm looking forward to reviewing and potentially merging the PR to the project.

PR: #43

**Comment by edwinkys** [comment]
I will check it out and review it.
