### ISSUE TITLE
FEAT: add collection api to retrieve record with filtered metadata

### ISSUE THREAD

**Issue by edwinkys** [oasysai/oasysdb#47]
### Purpose & use case

We should add an API for the `Collection` called maybe `filter` that takes in the condition and return a hash map of VectorID to Record. This filter API is useful for users who need to retrieve some of records which data match the provided condition.

**Comment by zzl-7** [comment]
Hi @edwinkys , is this issue open to contribution? If yes, is it possible to elaborate a bit on the ask here?
Thank you

**Comment by edwinkys** [comment]
Hey, thank you for being interested in contributing. This issue is currently suspended.

Essentially, we want to create a method of collection, `Collection.filter(...)` where calling this allows users to retrieve vector records based on filter on the metadata.

```rs
pub fn filter(...) -> Result<HashMap<VectorID, Record>, Error>
```

The problem is that due to the flexible nature of the `Metadata`, I'm still thinking of what is the best way to solve this problem. I'd love to hear your thoughts tho 😁

**Comment by zzl-7** [comment]
@edwinkys  Thanks for the response, I am still playing around with the repo in general so I think you would have better expertise in the direction of how filtering should go, as I dig around the code I will keep this ticket in mind, for now I don't have any thoughts on this 
thanks

**Comment by edwinkys** [comment]
No problem! Take your time and please let me know if you need any help or have any questions. I'd be happy to help 😁
