### ISSUE TITLE
FEAT: collection insert methods return vector id

### ISSUE THREAD

**Issue by edwinkys** [oasysai/oasysdb#51]
### Use case

When inserting a vector record to a collection, users need a way to get the newly inserted record vector ID. When users need to update or delete the vector records, this returned vector ID can be used as the input parameters to the methods.

### Proposed solution

Modify the return type and value of the `Collection.insert` method.

```rs
// Before
-> Result<(), Error>

// After
-> Result<VectorID, Error>
```

**Comment by noneback** [comment]
I'd like take this

**Comment by edwinkys** [comment]
Sounds good! Looking forward to seeing another PR 😁

**Comment by noneback** [comment]
pr: #60

**Comment by edwinkys** [comment]
Thank you for the PR! I have reviewed and merged them 😁
