### ISSUE TITLE
FEAT: add qol methods for vector id

### ISSUE THREAD

**Issue by edwinkys** [oasysai/oasysdb#53]
### Use case & proposed solution

This is a request to add several utility methods to help users use the `VectorID` struct better. These are some ideas for improvement:

- Type conversion from `VectorID` to `usize` and `u32`.
- Utility methods `to_usize` and `to_u32`.

**Comment by noneback** [comment]
I'd like take this

**Comment by edwinkys** [comment]
That's perfect! I'm looking forward to the PR 😁

**Comment by noneback** [comment]
pr: #61

**Comment by edwinkys** [comment]
Thank you for the PR! Merged it 😁
