### ISSUE TITLE
DISCUSS: indexfiy Integration

### ISSUE THREAD

**Issue by diptanu** [oasysai/oasysdb#65]
Love the project! Would love an integration with Indexify - https://github.com/tensorlakeai/indexify

We are building an online extraction and retrieval engine for any type of unstructured data. It has a pluggable interface for vector stores - https://github.com/tensorlakeai/indexify/blob/main/src/vectordbs/mod.rs

Content uploaded into Indexify can then be queried using SQL and Vector Search! 

Any thoughts?

**Comment by edwinkys** [comment]
Hi 👋 

I checkout Indexify and I think it's an interesting project. I think that OasysDB can be a great fit for Indexify. I am certainly interested to collaborate and make an integration.

I have a plan to integrate OasysDB with [llm-chain](https://github.com/sobelio/llm-chain) too and I'm how Indexify differentiates from LLM Chain?

**Comment by diptanu** [comment]
@edwinkys Thanks!  LLM Chain is a Rust crate, while Indexify is a distributed compute engine with the ability to create pipelines that execute in real time as data is ingested into the server! Here are some example use cases - https://getindexify.ai/usecases/pdf_extraction/  and https://getindexify.ai/usecases/video_rag/

The integration here is implementing the VectorDB interface and exposing a config value which allows users to select oasysdb as a backend vector store.

**Comment by edwinkys** [comment]
Oh that's pretty sick! The use-cases are also great fit for OasysDB. I am really interested to get OasysDB integrated into Indexify suites.

I assume, we get started from here? (https://github.com/tensorlakeai/indexify/blob/main/src/vectordbs/mod.rs)

And add oasysdb.rs just like lancedb.rs and qdrant.rs?

**Comment by diptanu** [comment]
@edwinkys Yes exactly! We are going to launch a blog soon, so let's come up with a nice use case to talk about the integration!

**Comment by edwinkys** [comment]
Yes, for sure! Can I add you in Discord so we can continute the conversation there about this integration?
